### ISSUE TITLE
 not found  sourceMap in sentry 

### ISSUE THREAD

**Issue by wjf-richard** [ikenfin/vite-plugin-sentry#13] opened 2022-06-07 07:03 UTC
![image](https://user-images.githubusercontent.com/24648326/172316594-a60134a2-aeec-4bbb-ad9e-7b54c5771c61.png)
![image](https://user-images.githubusercontent.com/24648326/172316836-a36313c9-8857-44f6-9c84-6a436bdc6c1e.png)

vue3.x
vite 2.7.13

**Comment by ikenfin** [comment] 2022-06-12 21:12
Hello! I cannot reproduce this bug, can you plz add more details? 
Also, check your `.sentryclirc` files - **configFile** can apply only `*.properties` format (instead of sectionized ini - just prefixed config labels, line `auth.token=<token>`)

Also, try to run your vite builder with `SENTRY_LOG_LEVEL=debug` env var to see what happens on @sentry/cli side

**Comment by ikenfin** [comment] 2022-08-08 13:30
Closing this for now as it seems problem was in misconfiguration. Feel free to reopen if problem still exist! 👍

**Closed by ikenfin** 2022-08-08 13:30 UTC
